version: "3.9"

services:
  # TeamCruz Database - PostgreSQL customizado na porta 5433
  teamcruz-db:
    image: postgres:15-alpine
    container_name: teamcruz-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: teamcruz_db
      POSTGRES_USER: teamcruz_admin
      POSTGRES_PASSWORD: cruz@jiujitsu2024
      TZ: 'America/Sao_Paulo'
    ports:
      - "5436:5432"  # Porta customizada para TeamCruz
    volumes:
      - teamcruz_postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:14
    container_name: acesso-usuarios-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: acesso_usuarios_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - acesso_usuarios_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: gestao-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/acesso_usuarios_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm/:/opt/keycloak/data/import/
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
    container_name: gestao-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - keycloak

  frontend:
    build:
      context: ./frontend
    container_name: gestao-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  acesso_usuarios_postgres_data:
  teamcruz_postgres_data:
