version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: acesso-usuarios-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acesso_usuarios_db
      POSTGRES_INITDB_ARGS: --auth-host=md5 --auth-local=trust
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: acesso-usuarios-backend
    ports:
      - '5002:5002'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: acesso_usuarios_db
      JWT_SECRET: meu-super-secret-jwt-key-2024
      JWT_EXPIRES_IN: 24h
      PORT: 5002
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:3000,http://localhost:3001,http://localhost:3002,http://127.0.0.1:3000,http://127.0.0.1:3001,http://127.0.0.1:3002
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
